### ISSUE TITLE
ModuleNotFoundError: No module named 'gpflow.multioutput'

### ISSUE THREAD

**Issue by X1AOX1A** [bperezorozco/ordinal_tsf#3]
When running the example.py, I occurred the following problem:

```PYTHON
Traceback (most recent call last):
  File "/Users/apple/Documents/Project/ordinal_tsf/example.py", line 4, in <module>
    from ordinal_tsf.model import MordredStrategy
  File "/Users/apple/Documents/Project/ordinal_tsf/ordinal_tsf/model.py", line 15, in <module>
    import gpflow.multioutput.features as mf
ModuleNotFoundError: No module named 'gpflow.multioutput'
```

My current gpflow version is 2.0.3, with Python 3.7, and I can't find the module 'gpflow.multioutput'.
Could you please specify the version of gpflow, or the environment of the experiment?

Thx!

**Comment by bperezorozco** [comment]
Hi Xavier,

Apologies for the lack of clarity as the repo is no longer maintained.

This work was done around summer last year, so looking at GPflow's release
history, this would have to be release 1.3 or 1.4.1.

Hope this helps,
Bernardo

**Comment by X1AOX1A** [comment]
Thx!
